<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://soap.srhm.ufro.cl" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://soap.srhm.ufro.cl" xmlns:intf="http://soap.srhm.ufro.cl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://soap.srhm.ufro.cl" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="obtenerEspecialidades">
    <complexType/>
   </element>
   <element name="obtenerEspecialidadesResponse">
    <complexType>
     <sequence>
      <element name="obtenerEspecialidadesReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="obtenerEspecialidadesRequest">

      <wsdl:part element="impl:obtenerEspecialidades" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="obtenerEspecialidadesResponse">

      <wsdl:part element="impl:obtenerEspecialidadesResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="EspecialidadSOAP">

      <wsdl:operation name="obtenerEspecialidades">

         <wsdl:input message="impl:obtenerEspecialidadesRequest" name="obtenerEspecialidadesRequest">

       </wsdl:input>

         <wsdl:output message="impl:obtenerEspecialidadesResponse" name="obtenerEspecialidadesResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="EspecialidadSOAPSoapBinding" type="impl:EspecialidadSOAP">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="obtenerEspecialidades">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="obtenerEspecialidadesRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="obtenerEspecialidadesResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="EspecialidadSOAPService">

      <wsdl:port binding="impl:EspecialidadSOAPSoapBinding" name="EspecialidadSOAP">

         <wsdlsoap:address location="http://localhost:8080/srhm-soap/services/EspecialidadSOAP"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
